### ISSUE TITLE
Power App Licensing Requirements

### ISSUE THREAD

**Issue by haroldbruce** [OfficeDev/microsoft-teams-apps-issuereporting#1]
The documentation should provide what licensing is required for this application.  Do App Passes work, do you need per-user license, etc.  

What are the licensing requirements for this to work for users.  Also, what roles should users be given.

**Comment by navjotm** [comment]
The purpose of this github page is to provide the unmanaged solutions for the Teams template apps being released on Teams store (https://aka.ms/TeamsSamplePowerApps).

These sample apps are designed for Dataverse for Teams - which are seeded in O365 licenses (https://docs.microsoft.com/en-us/power-platform/admin/about-teams-environment#licensing-and-restrictions). These apps can also be deployed on Dataverse, which will require premium licenses.

Refer to license guide for Power Platform for additional details: https://docs.microsoft.com/en-us/power-platform/admin/pricing-billing-skus
