### ISSUE TITLE
Solution will not import

### ISSUE THREAD

**Issue by seanpcook** [OfficeDev/microsoft-teams-apps-issuereporting#2]
When attempting to import the zip file as a solution an error message appears stating the correct files are not at the root of the compressed folder. See attachment for details.

![Screen Shot 2021-01-26 at 2 46 12 PM](https://user-images.githubusercontent.com/64341560/105896976-8a74ec00-5fe5-11eb-8ab4-eb6e7a40f660.png)

**Comment by haroldbruce** [comment]
Extract the zip downloaded and then re-zip it with a different name, that worked for us.  We are struggling with licenses and permissions/roles but no word from the author yet.

**Comment by seanpcook** [comment]
> Extract the zip downloaded and then re-zip it with a different name, that worked for us. We are struggling with licenses and permissions/roles but no word from the author yet.

Thanks so much haroldbruce. I see what the issue was there. Unfortunately I'm not able to help with your issue because I find it just as confusing. Powerapps is portrayed as a super simple solution but they seem to leave out the nuance behind the licensing and I've hit roadblocks multiple times. Currently I'm signed up with their developer program and using a development tenant with an E5 license so I'm not sure where I'll hit the wall at or how this will work if I attempt to bring it into my production tenant.

**Comment by haroldbruce** [comment]
Also, this solution does not work in the GCC/Gov cloud.

**Comment by navjotm** [comment]
Have updated the installation instructions to clarify. We plan to continue improving support for the unmanaged solutions on github.

Note that you can always get the latest copy of the apps from Teams store @ https://aka.ms/TeamsIssueReporting 
The teams store version is updated more frequently.

With regards to licensing - please contact your account representative. Additionally, you can refer to the licensing guide here: https://docs.microsoft.com/en-us/power-platform/admin/pricing-billing-skus
